name: EAS Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-username: ${{ secrets.USERNAME }}
          expo-password: ${{ secrets.PASSWORD }}

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Build on EAS
        run: npx eas-cli build --platform android --non-interactive
